name: Run HelloWorld Flow
on:
  push:

jobs:
  helloworld:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install and Configure Outerbounds
        run: |-
          pip install -U outerbounds && \
          outerbounds service-principal-configure \
          --name github-actions-demo \
          --deployment-domain dev-content.outerbounds.xyz \
          --perimeter default \
          --github-actions

      - name: Backtest model
        run: |-
          python hello.py run --with kubernetes

      - name: Deploy to production
        run: |-
          python hello.py --branch ${{ github.head_ref || github.ref_name }} argo-workflows create
